defaults: &metrics_clean_up
  description: "Cleans up / prunes expired metrics."
  class: Recurring::MetricsCleanUpJob
  queue: low
  schedule: every day at 12pm

development:
  metrics_clean_up:
    <<: *metrics_clean_up

production:
  metrics_clean_up:
    <<: *metrics_clean_up
