host: "<%= ENV.fetch("APP_HOST", "localhost") %>"
stripe:
  public_key: "pk_test"
  secret_key: "sk_test"
  payments_webhook_secret: "whsec_test"
oauth2:
  google:
    client_id: "google_oauth2_client_id"
    client_secret: "google_oauth2_client_id"
google:
  api:
    oauth:
      client_id: "client_id"
      client_secret: "secret"
      google_drive_refresh_token: "refresh_token"
backup:
  google_drive:
    folders:
      primary: "primary"
      queue: "queue"
      cable: "cable"
      cache: "cache"
      errors: "errors"
